version: '3.8'

services:
  vector:
    image: timberio/vector:latest-alpine
    container_name: vector
    ports:
      - "8686:8686"
    command: ["--config", "/etc/vector/vector.yaml"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      
      # FIX: Explicitly target the subdirectory path from the Git root
      - ./portainer/vector/vector_config:/etc/vector:ro
      - ./portainer/vector/vector_logs:/var/log/vector
    restart: unless-stopped
