version: '3.8'

services:
  vector:
    image: timberio/vector:latest-alpine
    container_name: vector
    ports:
      - "8686:8686"
    command: ["--config", "/etc/vector/vector.yaml"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      
      # Renamed to force Docker to create a fresh, clean folder
      - ./vector_config:/etc/vector:ro
      
      # Moved completely separate from the config folder
      - ./vector_logs:/var/log/vector
    restart: unless-stopped
